# Generated by Django 4.1 on 2022-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='contact',
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact',
            field=models.BigIntegerField(default=9876543210),
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(to='app2.teacher'),
        ),
    ]
